# %% [markdown]
# # Isometric Contraction: Coupled ToRORd + RDQ18 + Holzapfel-Ogden
#
# In this tutorial, we construct a 0D cardiac electromechanical simulation of an **isometric contraction**.
#
# Unlike the free contraction (isotonic) where the tissue shortens, here the tissue length is clamped.
# * **Knowns**: The stretch ratio ($\lambda$) is completely fixed.
# * **Unknowns**: We must find the hydrostatic pressure ($p$) to ensure the transverse boundaries remain stress-free ($P_{22} = 0$), and then calculate the total required holding stress in the fiber direction ($P_{11}$).

# %%
from pathlib import Path
from tqdm import tqdm
import urllib.request
import gotranx.cli.cellml2ode
import gotranx.cli.gotran2py

from scipy.optimize import root
import numpy as np
import numba
import matplotlib.pyplot as plt
import sympy  # noqa: F401
import zero_mech

from crossbridge import RDQ18

# %% [markdown]
# ## 1. Setting up the Tissue Mechanics Model
#
# We configure the `zero_mech` model identically to the free contraction case. We use the Holzapfel-Ogden passive material law, an incompressible constraint, and an active stress formulation.

# %%
experiment = zero_mech.experiments.uniaxial_tension()
mat = zero_mech.material.HolzapfelOgden()
comp = zero_mech.compressibility.Incompressible()
act = zero_mech.active.ActiveStress()

mech_model = zero_mech.Model(material=mat, compressibility=comp, active=act)

# Calculate the First Piola-Kirchhoff stress symbolically
P = mech_model.first_piola_kirchhoff(experiment.F)

# %% [markdown]
# ## 2. Generating and Initializing the EP Model
#
# We download and compile the ToRORd endocardial model into optimized Python code just as before.

# %%
module_path = Path("ToRORd_dynCl_endo.py")

if not module_path.is_file():
    print("Generating ToRORd_dynCl_endo.py from CellML...")
    url = "https://raw.githubusercontent.com/jtmff/torord/refs/heads/master/cellml/ToRORd_dynCl_endo.cellml"
    cellml_path = module_path.with_suffix(".cellml")
    urllib.request.urlretrieve(url, cellml_path)

    ode_path = module_path.with_suffix(".ode")
    gotranx.cli.cellml2ode.main(cellml_path, outname=ode_path)

    gotranx.cli.gotran2py.main(
        fname=ode_path,
        scheme=[gotranx.schemes.Scheme.generalized_rush_larsen],
        outname=module_path,
    )

import ToRORd_dynCl_endo as ep_model

# %% [markdown]
# ### Pre-pacing the EP Model
#
# We pre-pace the cell for 100 beats to ensure the calcium transient is stable before coupling the mechanics.

# %%
dt = 0.05
BCL = 400
num_beats = 3

t = np.arange(0, num_beats * BCL, dt)
t_one_beat = np.arange(0, BCL, dt)

y = ep_model.init_state_values()
params = ep_model.init_parameter_values(i_Stim_Period=BCL)

V_index = ep_model.state_index("v")
Ca_index = ep_model.state_index("cai")
fgr = numba.njit(ep_model.generalized_rush_larsen)

print("Running EP model to steady state...")
num_beats_pre = 100

# We don't need to store the pre-pacing traces this time, just update the state `y`
for beat_nr in tqdm(range(num_beats_pre), desc="Pre-pacing"):
    for ti in t_one_beat:
        y = fgr(y, ti, dt, params)

# %% [markdown]
# ## 3. Configuring the Isometric Mechanical Solver
#
# Because $\lambda$ is fixed, the deformation gradient $F$ is completely known. We only need to solve for the hydrostatic pressure $p$ that makes the transverse stress exactly zero ($P_{22} = 0$).


# %%
def func_iso(p_array, Ta, lmbda_fixed):
    """
    Residual function for the isometric root finder.
    We seek p such that the transverse 1st Piola-Kirchhoff stress (P22) is zero.
    """
    p = p_array[0]

    replace = {
        mech_model["p"]: p,
        mech_model["Ta"]: Ta,
        experiment["λ"]: lmbda_fixed,
        **mat.default_parameters(),
    }

    P22 = P[1, 1].xreplace(replace)
    return np.array([P22], dtype=np.float64)


# %% [markdown]
# ## 4. The Coupled Isometric Simulation Loop
#
# We will simulate the isometric twitch at a fixed stretch ratio of **1.0**.
# * In this configuration, the passive stretch is exactly zero, so all measured stress in the fiber direction ($P_{11}$) will be entirely generated by the active contraction ($T_a$).
# * You can experiment by changing `lmbda_fixed` to **1.05** (a 5% stretch). You will observe higher active tension due to the RDQ18 model's length-dependent activation rules, as well as an elevated baseline passive stress!

# %%
lmbda_fixed = 1.0  # Clamp the tissue at 100% of its resting length
p_value = 0.0

dt_mech = dt * 1e-3
dt_sarc = 2.5e-5

sarcomere_parms = RDQ18.default_parameters()
sarcomere_parms["dt"] = dt_sarc
# Resting sarcomere length (um)
sl0 = 2.2

sarcomere = RDQ18(num_cells=1, Ta_max=150.0, params=sarcomere_parms)

# Storage arrays
V = np.zeros(len(t))
Ca = np.zeros(len(t))
Ta = np.zeros(len(t))
P11s = np.zeros(len(t))
ps = np.zeros(len(t))

i = 0
for beat_nr in tqdm(range(num_beats), desc="Coupled Beats"):
    for ti in tqdm(t_one_beat, total=len(t_one_beat), desc="Time within beat", leave=False):
        # 1. Electrophysiology Step
        y = fgr(y, ti, dt, params)
        V[i] = y[V_index]
        Ca[i] = y[Ca_index]

        # 2. Sarcomere Step
        # The sarcomere length is totally static throughout the simulation
        current_SL = np.array([sl0 * lmbda_fixed])
        sarcomere.advance_ODE(dt_mech, Ca[i] * 1e3, current_SL)

        permissivity = sarcomere.compute_permissivity()[0]
        Ta[i] = sarcomere.Ta_max * permissivity

        # 3. Mechanics Step: Find p that ensures P22 = 0
        res = root(
            func_iso,
            np.array([p_value]),
            args=(Ta[i], lmbda_fixed),
            method="hybr",
        )
        p_value = res.x[0]
        ps[i] = p_value

        # 4. Evaluate the measured fiber stress (P11)
        replace_P11 = {
            mech_model["p"]: p_value,
            mech_model["Ta"]: Ta[i],
            experiment["λ"]: lmbda_fixed,
            **mat.default_parameters(),
        }
        P11s[i] = np.float64(P[0, 0].xreplace(replace_P11))

        i += 1

# %% [markdown]
# ## 5. Plotting the Isometric Results
#
# Since $\lambda$ is constant, we plot the measured Stress ($P_{11}$) instead. You will notice that the profile of $P_{11}$ closely matches $T_a$, which is the defining characteristic of an isometric uniaxial test around the resting length.

# %%
fig, ax = plt.subplots(2, 2, sharex=True, figsize=(10, 8))

# Electrophysiology
ax[0, 0].plot(t, V, color="blue")
ax[0, 0].set_ylabel("Membrane Potential (mV)")
ax[0, 0].set_title("Voltage")

ax[0, 1].plot(t, Ca, color="orange")
ax[0, 1].set_ylabel("Intracellular Ca (mM)")
ax[0, 1].set_title("Calcium Transient")

# Internal Active Tension
ax[1, 0].plot(t, Ta, color="red")
ax[1, 0].set_xlabel("Time (ms)")
ax[1, 0].set_ylabel("Active Tension, Ta (kPa)")
ax[1, 0].set_title("Internal Active Stress")

# Total Measured Tissue Stress
ax[1, 1].plot(t, P11s, color="darkgreen")
ax[1, 1].set_xlabel("Time (ms)")
ax[1, 1].set_ylabel("Total Fiber Stress, P11 (kPa)")
ax[1, 1].set_title(f"Measured Tissue Stress ($\lambda$={lmbda_fixed})")

for axi in ax.flatten():
    axi.grid(True, alpha=0.3)

fig.tight_layout()
fig.savefig("holzapfel_torord_isometric.png")
plt.show()
