# %% [markdown]
# # Coupling a 0D Electromechanics Model: ToRORd + RDQ18 + Holzapfel-Ogden
#
# In this tutorial, we will construct a fully coupled, zero-dimensional (0D) cardiac electromechanical simulation. We will link three distinct models:
#
# 1. **Electrophysiology (EP)**: The Tomek-Rodriguez (ToRORd) model, which simulates the cardiac action potential and intracellular calcium transient.
# [cite_start]2. **Sarcomere Mechanics**: The RDQ18 model, a highly efficient reduced-order ordinary differential equation (ODE) model for myofilament activation and crossbridge cycling[cite: 1]. [cite_start]It computes the fraction of permissive myosin heads based on nearest-neighbor cooperative interactions[cite: 1].
# 3. **Tissue Mechanics**: An incompressible Holzapfel-Ogden hyperelastic material model subjected to an active stress formulation.
#
# We will simulate an **unloaded free contraction**, meaning the virtual tissue block is free to shorten against zero external mechanical resistance.
#
# Let's start by importing our required libraries.

# %%
from pathlib import Path
from tqdm import tqdm
import os
import urllib.request
import gotranx.cli.cellml2ode
import gotranx.cli.gotran2py
from scipy.optimize import root
import numpy as np
import numba
import matplotlib.pyplot as plt
import sympy  # noqa: F401
import zero_mech

if os.getenv("CI"):

    def tqdm(*args, **kwargs):  # noqa: F811
        return args[0]


# Import the sarcomere model (RDQ18)
from crossbridge import RDQ18

# %% [markdown]
# ## 1. Setting up the Tissue Mechanics Model
#
# We use the `zero_mech` library to set up the macroscopic tissue mechanics.
# * We define a uniaxial tension experiment (pulling/contracting along the fiber direction).
# * The passive material response is governed by the **Holzapfel-Ogden** constitutive law.
# * The tissue is assumed to be **incompressible** (volume-preserving).
# * The active component is incorporated using an **Active Stress** approach, where the active tension ($T_a$) generated by the sarcomeres is added additively to the passive stress tensor in the fiber direction.
#
# Finally, we generate the symbolic First Piola-Kirchhoff ($P$) stress tensor.

# %%
experiment = zero_mech.experiments.uniaxial_tension()
mat = zero_mech.material.HolzapfelOgden()
comp = zero_mech.compressibility.Incompressible()
act = zero_mech.active.ActiveStress()

mech_model = zero_mech.Model(material=mat, compressibility=comp, active=act)

# Calculate the First Piola-Kirchhoff stress symbolically
P = mech_model.first_piola_kirchhoff(experiment.F)

# %% [markdown]
# ## 2. Generating the Electrophysiology (EP) Model
#
# Cardiac EP models are often distributed in CellML format. We will use `gotranx` to dynamically download the ToRORd endocardial model, convert it into an ODE format, and compile it into highly optimized Python code.
#
# We utilize the **Generalized Rush-Larsen** scheme, which provides excellent numerical stability for the stiff differential equations typically found in cardiac ionic models.

# %%
module_path = Path("ToRORd_dynCl_endo.py")

# Generate code and save it to a file if it does not exist
if not module_path.is_file():
    print("Generating ToRORd_dynCl_endo.py from CellML...")
    url = "https://raw.githubusercontent.com/jtmff/torord/refs/heads/master/cellml/ToRORd_dynCl_endo.cellml"
    cellml_path = module_path.with_suffix(".cellml")
    urllib.request.urlretrieve(url, cellml_path)

    ode_path = module_path.with_suffix(".ode")
    gotranx.cli.cellml2ode.main(cellml_path, outname=ode_path)

    gotranx.cli.gotran2py.main(
        fname=ode_path,
        scheme=[gotranx.schemes.Scheme.generalized_rush_larsen],
        outname=module_path,
    )

import ToRORd_dynCl_endo as ep_model

# %% [markdown]
# ## 3. Initialization and EP Pre-Pacing
#
# Cardiac EP models can take a long time to reach a stable limit cycle (steady state). Before we couple the mechanics, we will "pre-pace" the isolated EP model for 100 beats.
#
# * **Time Step (`dt`)**: 0.05 ms.
# * **Basic Cycle Length (`BCL`)**: 400 ms (equivalent to 150 BPM).

# %%
# Temporal parameters
dt = 0.05
BCL = 400
num_beats = 3

# Setup time arrays
t = np.arange(0, num_beats * BCL, dt)
t_one_beat = np.arange(0, BCL, dt)
assert len(t) == len(t_one_beat) * num_beats, "Time array length mismatch"

# Initialize state and parameters from the generated EP model
y = ep_model.init_state_values()
params = ep_model.init_parameter_values(i_Stim_Period=BCL)

# Retrieve indices for variables we need to track/pass to the mechanics
V_index = ep_model.state_index("v")  # Membrane potential
Ca_index = ep_model.state_index("cai")  # Intracellular Calcium

Istim_index = ep_model.monitor_index("Istim")
fgr = numba.njit(ep_model.generalized_rush_larsen)
mon = ep_model.monitor_values

# %% [markdown]
# ### Running the Pre-Pacing Loop
# We simulate 100 beats and record the voltage and calcium transients to ensure the model has stabilized.

# %%
print("Running EP model to steady state...")
num_beats_pre = 100
Vs = np.zeros(len(t_one_beat) * num_beats_pre)
Cas = np.zeros(len(t_one_beat) * num_beats_pre)

i = 0
for beat_nr in tqdm(range(num_beats_pre), desc="Pre-pacing"):
    for ti in t_one_beat:
        y = fgr(y, ti, dt, params)
        Vs[i] = y[V_index]
        Cas[i] = y[Ca_index]
        i += 1

# Plot the steady-state EP results
fig, ax = plt.subplots(2, 1, sharex=True)
ax[0].plot(Vs)
ax[0].set_ylabel("V (mV)")
ax[1].plot(Cas)
ax[1].set_ylabel("Ca (mM)")
ax[1].set_xlabel("Time (ms)")
fig.tight_layout()
fig.savefig("ep_steady_state.png")

# Close the figure

plt.close(fig)

# %% [markdown]
# ## 4. Configuring the Electromechanical Coupling
#
# To solve the mechanics, we need to find the mechanical equilibrium at each time step. Since we are simulating an **unloaded free contraction**, the external forces are zero. Therefore, we must find the fiber stretch ratio (`lmbda`, $\lambda$) and the hydrostatic pressure (`p`) that result in zero stress in both the fiber direction ($P_{11}$) and the transverse direction ($P_{22}$).
#
# We define a residual function `func` that `scipy.optimize.root` will use to drive $P_{11}$ and $P_{22}$ to zero.


# %%


def func(x, Ta):
    """
    Residual function for the mechanical root finder.
    We seek lmbda and p such that the 1st Piola-Kirchhoff stress components are zero.
    """
    lmbda, p = x

    # Substitute current numerical values into the symbolic stress tensor expressions
    replace = {
        mech_model["p"]: p,
        mech_model["Ta"]: Ta,
        experiment["λ"]: lmbda,
        **mat.default_parameters(),
    }

    P11 = P[0, 0].xreplace(replace)
    P22 = P[1, 1].xreplace(replace)

    return np.array([P11, P22], dtype=np.float64)


# %% [markdown]
# ### Initializing the RDQ18 Sarcomere Model
#
# The RDQ18 model bridges the EP and tissue scales.
# [cite_start]* **Input**: It receives intracellular calcium $c(t)$ and sarcomere length $SL(t)$[cite: 1].
# [cite_start]* **Output**: It yields the fraction of permissive myosin heads, which determines the active force[cite: 1].
#
# **Critical Unit Management**:
# * The EP model (ToRORd) computes time in **ms** and calcium in **mM**.
# * The RDQ18 model natively expects time in **seconds** and calcium in **$\mu$M**.
# We must carefully convert these during the coupling loop.

# %%
lmbda_value = 1.0
prev_lmbda = lmbda_value
p_value = 0.0

# Time step conversions for the sarcomere model
dt_mech = dt * 1e-3  # Convert ms to seconds
dt_sarc = 2.5e-5  # Internal ODE time step for RDQ18 stability

# Setup RDQ18 parameters
sarcomere_parms = RDQ18.default_parameters()
sarcomere_parms["dt"] = dt_sarc
# Resting sarcomere length (usually ~2.2 um)
sl0 = 2.2

# Initialize the model (Ta_max scales the normalized permissivity to physical stress)
sarcomere = RDQ18(num_cells=1, Ta_max=150.0, params=sarcomere_parms)

# %% [markdown]
# ## 5. The Coupled Electromechanical Simulation Loop
#
# We will now simulate 3 complete heartbeats. At each time step, we execute a segregated coupling strategy:
# 1. Step the EP model to get the new Calcium concentration.
# 2. Pass Calcium and the *current* Sarcomere Length to the RDQ18 model to step its internal states and compute the Active Tension ($T_a$).
# 3. Pass $T_a$ to the mechanics root-finder to compute the new geometric stretch ($\lambda$).

# %%
# Allocate storage arrays for the results
V = np.zeros(len(t))
Ca = np.zeros(len(t))
Ta = np.zeros(len(t))
Istim = np.zeros(len(t))
lmbdas = np.zeros(len(t))
dLambdas = np.zeros(len(t))
ps = np.zeros(len(t))

i = 0
for beat_nr in tqdm(range(num_beats), desc="Coupled Beats"):
    for ti in tqdm(t_one_beat, total=len(t_one_beat), desc="Time within beat", leave=False):
        # 1. Electrophysiology Step
        y = fgr(y, ti, dt, params)
        V[i] = y[V_index]
        Ca[i] = y[Ca_index]

        # 2. Sarcomere Step
        # Note: Ca is multiplied by 1e3 to convert mM -> uM.
        # Sarcomere length is the resting length multiplied by the stretch ratio.
        current_SL = np.array([sl0 * lmbda_value])
        sarcomere.advance_ODE(dt_mech, Ca[i] * 1e3, current_SL)

        # Retrieve active tension (Permissivity * Maximum Tension)
        permissivity = sarcomere.compute_permissivity()[0]
        Ta[i] = sarcomere.Ta_max * permissivity

        # 3. Mechanics Step
        # Solve for lambda and p to ensure zero global stress (free contraction)
        res = root(
            func,
            np.array([lmbda_value, p_value]),
            args=(Ta[i],),
            method="hybr",
        )
        lmbda_value, p_value = res.x

        # Store mechanical data
        lmbdas[i] = lmbda_value
        ps[i] = p_value
        dLambdas[i] = (lmbda_value - prev_lmbda) / dt
        prev_lmbda = lmbda_value

        i += 1

# %% [markdown]
# ## 6. Results and Visualization
#
# Let's plot the results of our coupled simulation. We expect to see the action potential trigger the calcium transient, which in turn generates active tension. Because the tissue is unloaded, the generation of active tension will cause the stretch ratio ($\lambda$) to drop below 1.0 (indicating tissue shortening).

# %%
fig, ax = plt.subplots(2, 3, sharex=True, figsize=(14, 8))

# Electrophysiology
ax[0, 0].plot(t, V, color="blue")
ax[0, 0].set_ylabel("Membrane Potential (mV)")
ax[0, 0].set_title("Voltage")

ax[0, 1].plot(t, Ca, color="orange")
ax[0, 1].set_ylabel("Intracellular Ca (mM)")
ax[0, 1].set_title("Calcium Transient")

# Sarcomere Force
ax[1, 0].plot(t, Ta, color="red")
ax[1, 0].set_xlabel("Time (ms)")
ax[1, 0].set_ylabel("Active Tension, Ta (kPa)")
ax[1, 0].set_title("Active Stress Generation")

# Macroscopic Kinematics
ax[0, 2].plot(t, lmbdas, color="green")
ax[0, 2].set_ylabel(r"Stretch Ratio, $\lambda$")
ax[0, 2].set_title("Tissue Shortening")

ax[1, 1].plot(t, dLambdas, color="purple")
ax[1, 1].set_xlabel("Time (ms)")
ax[1, 1].set_ylabel(r"Stretch Rate ($d\lambda/dt$)")
ax[1, 1].set_title("Shortening Velocity")

ax[1, 2].plot(t, ps, color="brown")
ax[1, 2].set_xlabel("Time (ms)")
ax[1, 2].set_ylabel("Hydrostatic Pressure, p (kPa)")
ax[1, 2].set_title("Incompressibility Enforcement")

for axi in ax.flatten():
    axi.grid(True, alpha=0.3)

fig.tight_layout()
fig.savefig("holzapfel_torord_coupled.png")
plt.show()
