"""Generate `src/crossbridge/rdq20mf.ode`, the gotranx file of `crossbridge.RDQ20MF`.

The regulatory-unit state is a (2, 2, 2, 2) tensor, which makes 16 hand-written
states and right-hand sides too repetitive to maintain, so the file is written by
this script instead:

    python3 tools/generate_rdq20mf_ode.py

Change the equations here, never in the generated file;
`tests/test_rdq20mf_ode_generator.py` fails if the two differ, and
`tests/test_ode_files.py` pins the result to the class.

State naming: `x_{a}{b}{c}{B}` is `x_RU[a, b, c, B]`, the joint probability of
(T_{i-1}, T_i, T_{i+1}, C_i), and `mu0_P, mu1_P, mu0_N, mu1_N` are
`x_XB[0, 0], x_XB[1, 0], x_XB[0, 1], x_XB[1, 1]`.

The equations are those of `RDQ20MF._RU_get_rhs`, `_XB_system` and the tension
getters, but every state advances together: the class steps the RU states by
explicit Euler at dt_RU, the crossbridges every 40th step and the rates every 10th,
so its tension sits about 0.5-0.8% of the peak from this ODE's, depending on the
protocol. The file follows the contract of the other models: component `inputs`
(Ca [uM], SL [um], dSL [um/s]), outputs Ta [kPa], Ka [kPa per unit Lambda] and
bound_ca [fraction], parameters as in `default_parameters()` (without dt, Ca0 and
dt_RU), initial states as `reset()`.
"""

import itertools
from pathlib import Path

B4 = list(itertools.product((0, 1), repeat=4))  # (a, b, c, B)


def x(a, b, c, B):
    return f"x_{a}{b}{c}{B}"


def kT(a, b, c, B):
    n = a + c  # permissive neighbours
    if b == 1:
        return f"Kbasic * gamma**{2 - n}"
    return f"Q * Kbasic * gamma**{n}" + (" / mu" if B == 0 else "")


def guarded(num, den, name):
    return f"{name} = Conditional(Gt({den}, 0.0), ({num}) / ({den}), 0.0)"


HEADER = [
    "# RDQ20-MF (Regazzoni, Dede', Quarteroni 2020), as crossbridge.RDQ20MF implements it.",
    "# GENERATED by tools/generate_rdq20mf_ode.py: change the generator, not this file.",
    "# Loaded through RDQ20MF.ODE_FILE; tests/test_ode_files.py pins it to the class.",
    "#",
    "# Units: s, uM, um; Ta and Ka are reported in kPa (Ka per unit Lambda).",
    "#",
    "# The contract: the component `inputs` holds Ca, SL and dSL. Standalone they are",
    "# parameters; subtracting the component turns them into missing variables. The outputs",
    "# are the intermediates Ta, Ka and bound_ca.",
    "# States: x_abcB = x_RU[a, b, c, B]; mu0_P, mu1_P, mu0_N, mu1_N =",
    "# x_XB[0, 0], x_XB[1, 0], x_XB[0, 1], x_XB[1, 1].",
    "",
]


def kC(B, b):  # rate of leaving calcium state B given T_i = b
    if B == 0:
        return "Kon_Ca"
    return "Koff" if b == 0 else "Koff / mu"


def phis(a, b, c, B):
    return {
        "L": f"kT_L_{a}{b} * {x(a, b, c, B)}",
        "C": f"PhiT_C_{a}{b}{c}{B}",
        "R": f"kT_R_{b}{c} * {x(a, b, c, B)}",
        "Ca": f"{kC(B, b)} * {x(a, b, c, B)}",
    }


def main() -> str:
    lines = [
        *HEADER,
        'parameters("inputs", Ca = 0.1, SL = 2.2, dSL = 0.0)',
        "",
        'parameters("rdq20mf",',
        "LA = 1.25, LM = 1.65, LB = 0.18, SL0 = 2.2, mu = 10.0, gamma = 12.0, Q = 2.0,",
        "Kd0 = 0.381, alphaKd = -0.571, Koff = 100.0, Kbasic = 13.0,",
        "r0 = 134.31, alpha = 25.184, mu0_fP = 32.653, mu1_fP = 0.778, a_XB = 22894.0",
        ")",
        "",
        'states("RU", '
        + ", ".join(f"{x(*s)} = {1.0 if s == (0, 0, 0, 0) else 0.0}" for s in B4)
        + ")",
        'states("XB", mu0_P = 0.0, mu1_P = 0.0, mu0_N = 0.0, mu1_N = 0.0)',
        "",
        'expressions("RU")',
        "Kd = Kd0 - alphaKd * (2.15 - SL)",
        "Kon_Ca = Koff / Kd * Ca",
    ]
    # Central fluxes PhiT_C[a,b,c,B] = x * kT
    for s in B4:
        lines.append(f"PhiT_C_{''.join(map(str, s))} = {x(*s)} * {kT(*s)}")
    # Mean-field rates of the left and right neighbours
    for b, c in itertools.product((0, 1), repeat=2):
        num = " + ".join(f"PhiT_C_{a}{b}{c}{B}" for a in (0, 1) for B in (0, 1))
        den = " + ".join(x(a, b, c, B) for a in (0, 1) for B in (0, 1))
        lines.append(guarded(num, den, f"kT_L_{b}{c}"))
    for a, b in itertools.product((0, 1), repeat=2):
        num = " + ".join(f"PhiT_C_{a}{b}{c}{B}" for c in (0, 1) for B in (0, 1))
        den = " + ".join(x(a, b, c, B) for c in (0, 1) for B in (0, 1))
        lines.append(guarded(num, den, f"kT_R_{a}{b}"))

    for a, b, c, B in B4:
        out = phis(a, b, c, B)
        inn = [
            phis(1 - a, b, c, B)["L"],
            phis(a, 1 - b, c, B)["C"],
            phis(a, b, 1 - c, B)["R"],
            phis(a, b, c, 1 - B)["Ca"],
        ]
        rhs = " - ".join(["(" + " + ".join(inn) + ")", "(" + " + ".join(out.values()) + ")"])
        lines.append(f"d{x(a, b, c, B)}_dt = {rhs}")

    perm = " + ".join(x(a, 1, c, B) for a in (0, 1) for c in (0, 1) for B in (0, 1))
    lines += [
        f"perm = {perm}",
        "bound_ca = " + " + ".join(x(a, b, c, 1) for a in (0, 1) for b in (0, 1) for c in (0, 1)),
        "",
        'expressions("XB")',
    ]
    for T, name in ((1, "k_PN"), (0, "k_NP")):
        num = " + ".join(
            f"{x(a, T, c, B)} * {kT(a, T, c, B)}" for a in (0, 1) for c in (0, 1) for B in (0, 1)
        )
        den = " + ".join(x(a, T, c, B) for a in (0, 1) for c in (0, 1) for B in (0, 1))
        lines.append(guarded(num, den, name))
    lines += [
        "v = -dSL / SL0",
        "r = r0 + alpha * Abs(v)",
        "dmu0_P_dt = -(r + k_PN) * mu0_P + k_NP * mu0_N + perm * mu0_fP",
        "dmu1_P_dt = -v * mu0_P - (r + k_PN) * mu1_P + k_NP * mu1_N + perm * mu1_fP",
        "dmu0_N_dt = k_PN * mu0_P - (r + k_NP) * mu0_N",
        "dmu1_N_dt = k_PN * mu1_P - v * mu0_N - (r + k_NP) * mu1_N",
        "",
        'expressions("tension")',
        "LMh = (LM - LB) * 0.5",
        "frac_SO = Conditional(And(Gt(SL, LA), Le(SL, LM)), SL - LA,"
        " Conditional(And(Gt(SL, LM), Le(SL, 2*LA - LB)), (SL + LM - 2*LA) * 0.5,"
        " Conditional(And(Gt(SL, 2*LA - LB), Le(SL, 2*LA + LB)), LMh,"
        " Conditional(And(Gt(SL, 2*LA + LB), Le(SL, 2*LA + LM)),"
        " (LM + 2*LA - SL) * 0.5, 0.0)))) / LMh",
        "Ta = a_XB * (mu1_P + mu1_N) * frac_SO",
        "Ka = a_XB * (mu0_P + mu0_N) * frac_SO",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    path = Path(__file__).resolve().parents[1] / "src" / "crossbridge" / "rdq20mf.ode"
    path.write_text(main())
